name: CD - Statocles

on: 
  pull_request:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  perl-job:
    runs-on: ['ubuntu-latest']
    container:
      image: perl
    strategy:
      fail-fast: true
    name: build and publish 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        name: Do checkout
      - name: Setup Perl environment
        run: |
          echo PERL5LIB="$(pwd)/lib:$(pwd)/local/lib/perl5${PERL5LIB:+:PERL5LIB}" >> $GITHUB_ENV
          echo PERL_VERSION="$(perl -E 'print $^V')" >> $GITHUB_ENV
          cat .env >> $GITHUB_ENV
          echo "$(pwd)/local/bin" >> $GITHUB_PATH
      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch --track ${{ env.PUBLISH_BRANCH }} origin/${{ env.PUBLISH_BRANCH }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: local
          key: ${{ runner.os }}-cache-deps-${{ env.PERL_VERSION }}-${{ hashFiles('cpanfile') }}
      - name: Get dependencies
        run: |
          cpanm --notest --verbose Carton
          carton install
      - name: Build site for PR
        if: github.event_name == 'pull_request'
        run: |
          if [ "x${GITHUB_EVENT_NAME}" == "xpull_request" -a "x${GITHUB_BASE_REF}" == "x${SITE_BRANCH}" ]; then
            echo Running deploy job ! ${GITHUB_EVENT_NAME} ! ${GITHUB_REF} ! ${GITHUB_BASE_REF} !
            echo Detected pull request for pages, doing test build
            cd site/
            statocles build
          else
            echo Not a pull request for website not testing builds
          fi
      - name: Publish site
        if: github.event_name == 'push'
        run: |
          # fak it, just use some bash scripting
          if [ "x${GITHUB_EVENT_NAME}" == "push" -a "x${GITHUB_REF}" == "x${SITE_BRANCH}" ]; then
            echo Running deploy job . ${GITHUB_EVENT_NAME} . ${GITHUB_REF} . ${GITHUB_BASE_REF} .
            git stash -u
            cd site/
            statocles deploy
          else
            echo Not a push to the site branch, not deploying
          fi
